Repository dis-moi/extension, pull requests merged in 2020-09, with the labels that each got.

#685 feat(profiles): add pagination to contributor’s notices list
  src/api/fetchNotice.ts
  src/app/actions/contributor.ts
  src/app/actions/notices.ts
  src/app/lmem/contributor.ts
  src/app/profiles/App/Profiles/Profile/Profile.stories.tsx
  src/app/profiles/App/Profiles/Profile/Profile.tsx
  src/app/profiles/App/Profiles/Profile/ProfileNoticeList.tsx
  src/app/profiles/App/Profiles/Profile/withConnect.ts
  src/app/profiles/App/Profiles/SubscribePopin.tsx
  src/app/profiles/store/actions/index.ts
  src/app/profiles/store/actions/notices.ts
  src/app/profiles/store/reducers/notices.reducer.ts
  src/app/profiles/store/sagas/contributor.saga.ts
  src/app/profiles/store/sagas/notices.saga.ts
  src/app/profiles/store/selectors/index.ts
  src/app/profiles/store/selectors/notices.ts
  src/app/store/collection/reducers/index.ts
  src/app/store/collection/reducers/items.ts
  src/app/store/collection/reducers/offset.ts
  src/app/store/collection/selectors.ts
  src/app/store/sagas/effects/takeLatestLocationChange.ts
  src/app/store/sagas/fetchNotices.saga.ts
Labels: enhancement ✨, reviewable

#688 fix: profiles crashes because featured notices does not have relayersIds
  src/api/fetchNotice.ts
  src/app/actions/notices.ts
  src/app/background/reducers/resources/index.ts
  src/app/background/reducers/resources/notices.reducer.ts
  src/app/background/reducers/tabs.reducer.ts
  src/app/background/sagas/tab.ts
  src/app/background/selectors/prefs.ts
  src/app/content/App/Notice/Details/index.tsx
  src/app/content/App/Notice/List/index.tsx
  src/app/content/reducers/notices.ts
  src/app/lmem/notice.ts
  src/app/profiles/App/Profiles/Profile/Profile.tsx
  src/app/profiles/App/Profiles/Profile/ProfileNoticeList.tsx
  src/app/profiles/App/Profiles/Profile/ProfileNoticeListItem.tsx
  src/app/profiles/store/reducers/notices.reducer.ts
  src/app/profiles/store/selectors/index.ts
  src/app/profiles/store/selectors/notices.ts
  src/components/organisms/Notice/Notice.tsx
  src/components/organisms/NoticeDetails/NoticeDetails.tsx
  test/fakers/generateNotice.ts
Labels: bug 🐞, high priority, reviewable

#691 fix(subscribe): Fix subscription to a similar contributor.
  src/app/profiles/App/Profiles/Profile/Profile.tsx
  src/app/profiles/App/Profiles/Profile/withConnect.ts
  src/app/profiles/App/Profiles/SubscribePopin.tsx
  src/components/organisms/Contributor/ContributorCompact.tsx
Labels: bug 🐞

#686 fix(FeaturedNotice): resets max-width to improve display on mobile
  src/app/profiles/App/Profiles/Profile/FeaturedNotice.tsx
Labels: reviewable

#687 fix(banner): Fix default banner not showing up.
  webpack.profiles.config.js
Labels: bug 🐞

#695 fix: Similar profiles username/avatar is clickable again
  src/app/profiles/App/Profiles/Profile/SimilarProfiles.tsx
Labels: bug 🐞
