Repository dis-moi/extension, pull requests merged in 2020-07, with the labels that each got.

#649 Various profiles fixes
  src/app/background/sagas/connect.saga.ts
  src/app/background/sagas/subscriptions.saga.ts
  src/app/background/sagas/subscriptions.ts
  src/app/profiles/store/sagas/portConnection.saga.ts
Labels: bug 🐞

#654 chore: remove `profiles` app from extension package
  webpack.profiles.config.js
  webpack/config.plugins.js
Labels: bug 🐞, high priority, important, reviewable

#650 chore(extension-detection): Only post message if the location match t…
  src/app/content/index.ts
Labels: enhancement ✨

#657 feat(Stats): removes contributions number everywhere
  src/app/options/App/Settings/SubscriptionsScreen/SubscriptionsScreen.tsx
  src/app/profiles/App/Profiles/Profile/ProfileIntro.tsx
  src/app/profiles/App/Profiles/Profile/SimilarProfiles.tsx
  src/components/atoms/Contributor/ContributorCard.ts
  src/components/atoms/Contributor/ContributorInfos.ts
  src/components/atoms/Stat/Stat.stories.tsx
  src/components/atoms/Stat/Stat.ts
  src/components/atoms/Stat/StatType.ts
  src/components/organisms/Contributor/ContributorCompact.tsx
  src/components/organisms/Contributor/ContributorLarge.tsx
Labels: reviewable

#662 feat(onboarding): remove contributor 51 from defaults
  src/app/lmemContributors.ts
Labels: enhancement ✨, reviewable

#667 fix: Browser action click not toggling UI
  src/app/actions/tabs.ts
  src/app/background/sagas/lib/sendToTab.saga.ts
  src/app/background/sagas/tab.ts
  src/app/lmem/tab.ts
  src/webext/createBrowserActionListener.ts
  test/app/actions.ts
Labels: bug 🐞

#664 chore: Change refresh intervals to values that make some sense
  .env.development.example
  .env.proding
  .env.production
  .env.staging
  src/app/background/sagas/refreshMatchingContexts.ts
Labels: enhancement ✨

#669 Fix/restablish active tab permission
  README.md
  manifest/base.js
  src/app/actions/tabs.ts
  src/app/background/sagas/lib/sendToTab.saga.ts
  src/app/background/sagas/tab.ts
  src/app/lmem/tab.ts
  src/webext/createBrowserActionListener.ts
  test/app/actions.ts
Labels: bug 🐞

#670 fix: use meta URL in ratings actions instead of tabs.query
  src/api/postRating.ts
  src/app/actions/index.ts
  src/app/actions/notices.ts
  src/app/background/reducers/tabs.reducer.ts
  src/app/background/sagas/ratings/notices.saga.ts
  src/app/background/sagas/tracking/trackNotice.saga.ts
  src/app/content/sagas/notices.ts
  src/components/organisms/Notice/Notice.tsx
  src/components/organisms/NoticeDetails/NoticeDetails.tsx
  src/webext/getSelectedTab.ts
Labels: bug 🐞

#671 fix(matching-contexts): Fix all matching contexts being fetched after…
  src/app/actions/refreshMatchingContexts.ts
  src/app/background/sagas/refreshMatchingContexts.ts
  src/app/profiles/store/reducers/index.ts
  src/app/profiles/store/sagas/index.ts
  src/app/profiles/store/sagas/matchingContexts.saga.ts
  src/app/store/sagas/refreshMatchingContexts.saga.ts
Labels: bug 🐞
