Repository dis-moi/extension, pull requests merged in 2020-11, with the labels that each got.

#725 chore: fix profiles Webpack rules
  webpack.profiles.config.js
Labels: bug 🐞

#733 chore: separate SENTRY_ENABLED and SENTRY_SEND_VERSION
  .env.development.example
  .env.example
  .env.proding
  .env.production
  .env.staging
  docs/CONTRIBUTING.md
  package.json
  release.config.js
  webpack/config.plugins.js
Labels: enhancement ✨, high priority, hot-fix 🚧, important, reviewable

#737 fix(contribution): track sendInBlue errors in Sentry
  src/app/content/sagas/contribution.ts
  src/app/content/sagas/question.ts
  src/app/sagas/effects/callAndRetry.ts
  src/app/sagas/error.ts
Labels: bug 🐞, enhancement ✨, hot-fix 🚧, reviewable, trelloized

#747 fix(DetailsContent): changes margins to improve readibility
  src/components/organisms/NoticeDetails/DetailsContent.ts
  src/components/organisms/NoticeDetails/Message.tsx
Labels: reviewable

#749 fix(NotConnectedPopin): sets width. fix #748
  src/app/profiles/App/Pages/Profiles/NotConnectedPopin.tsx
Labels: reviewable

#736 feat(matcher): Allow to match a page based on its content
  .eslintrc.json
  docs/MATCHERS.md
  src/app/background/sagas/tab.ts
  src/app/background/selectors/index.ts
  src/app/content/api.ts
  src/app/lmem/matchingContext.ts
  src/app/utils/doesDocumentMatchExpression.ts
  src/webext/contentScript.ts
  src/webext/createActionsListener.ts
  src/webext/createMessageHandler.ts
  test/app/lmem/findMatchingOffersAccordingToPreferences.ts
Labels: reviewable
