Repository dis-moi/extension, pull requests merged in 2020-08, with the labels that each got.

#672 fix(detection): matching contexts are not fetched at startup
  src/app/background/sagas/refreshMatchingContexts.ts
Labels: bug 🐞, high priority, hot-fix 🚧, important, reviewable

#675 fix(options): avatars in sidebars are normal size (should be small)
  src/components/organisms/Contributor/ContributorCompact.tsx
Labels: bug 🐞, reviewable

#676 fix(storybook): storybook won’t build
  webpack/config.rules.js
Labels: bug 🐞, reviewable

#677 Fix/profiles names
  src/app/profiles/App/Profiles/Profile/Profile.tsx
  src/app/profiles/App/Profiles/Profile/ProfileIntro.tsx
Labels: reviewable

#678 fix(FeaturedNotice): aligns image on the left for mobiles
  src/app/profiles/App/Profiles/Profile/FeaturedNotice.tsx
Labels: reviewable

#679 fix(profiles): changes on profiles details
  src/app/profiles/App/Profiles/Profile/ProfileNoticeListItem.tsx
  src/components/atoms/icons/Pin.tsx
  src/components/atoms/icons/index.ts
Labels: reviewable

#680 fix(profiles): changes sidebar button width
  src/app/profiles/App/Profiles/Profile/Profile.tsx
Labels: reviewable

#655 feat(contributors filters): styles the filters
  src/app/profiles/App/Profiles/List/ProfileList.tsx
  src/components/atoms/Tab/Tab.tsx
  src/components/molecules/Filters/Filters.stories.tsx
  src/components/molecules/Filters/FiltersCheckboxes.tsx
  src/components/molecules/Filters/FiltersSelect.tsx
  src/components/molecules/TabsNav/Container.tsx
Labels: enhancement ✨, mergeable 🚀

#681 fix: set fetch to use CORS mode
  src/api/call.ts
  src/app/profiles/store/sagas/contributors.saga.ts
Labels: bug 🐞

#683 fix(notification): avatar size in notice detail
  src/components/organisms/NoticeDetails/NoticeDetails.tsx
Labels: bug 🐞, reviewable

#684 fix(profileBanner): improves responsives display
  src/app/profiles/App/Profiles/Profile/ProfileBanner.tsx
Labels: reviewable

#682 feat(profile): strip protocol from example URL
  src/app/profiles/App/Profiles/Profile/ProfileNoticeListItem.tsx
  src/app/utils/stripUrlProtocol.ts
Labels: enhancement ✨, reviewable
