Repository dis-moi/extension, pull requests merged in 2021-07, with the labels that each got.

#1073 fix(storybook): import
  .storybook/preview.tsx
Labels: bug 🐞

#1078 Feat/order by subscribers
  src/app/profiles/App/Pages/Profiles/Profile/ProfileIntro.tsx
  src/app/profiles/store/reducers/contributors.reducer.ts
  src/app/profiles/store/selectors/contributors.ts
  src/components/organisms/Contributor/ContributorLarge.tsx
  src/libs/domain/contributor.ts
  src/libs/i18n/format.ts
  src/libs/i18n/resources/en/profiles.json
  src/libs/i18n/resources/fr/profiles.json
  src/libs/utils/sortByLocale.ts
  test/fakers/generateContributor.ts
Labels: feature ✨

#1059 feat(search): search on ProfilesList
  src/app/profiles/App/Pages/Profiles/List/ProfileList.tsx
  src/app/profiles/App/Pages/Subscriptions/Subscriptions.tsx
  src/app/profiles/App/useContributorsFilters.ts
  src/app/profiles/App/useContributorsRadiosFilters.ts
  src/components/atoms/Forms/Input/Input.ts
  src/components/atoms/icons/Search.tsx
  src/components/atoms/icons/index.ts
  src/libs/i18n/resources/en/profiles.json
  src/libs/i18n/resources/fr/profiles.json
  src/libs/utils/getSearch.spec.ts
  src/libs/utils/getSearch.ts
Labels: feature ✨

#1049 fix(ProfileBanner): changes image
  src/app/profiles/App/Pages/Profiles/Profile/ProfileBanner.tsx
  src/assets/img/profile-banner.jpg
  src/assets/img/profile-banner.png
Labels: design, profiles :busts_in_silhouette:

#989 refactor(i18n): avoid crash date
  src/libs/i18n/date.ts
  src/libs/i18n/format.ts
Labels: bug 🐞, i18n :gb:

#996 chore(Profiles/Notice)
  src/app/profiles/App/Pages/Profiles/Profile/ProfileIntro.tsx
  src/app/profiles/App/Pages/Profiles/Profile/ProfileNoticeListItem.tsx
Labels: design, profiles :busts_in_silhouette:

#762 chore: Differentiate 4xx Http errors from an actual server error
  src/libs/api/APIStatusCodeError.ts
  src/libs/api/call.ts
Labels: low priority

#1087 fix: fallback lng not recognized on init
  src/libs/i18n/date.ts
Labels: bug 🐞

#1071 feat(onboarding): trigger welcome bulle
  src/app/profiles/App/OnBoarding/LazyOnBoarding.tsx
  src/app/profiles/App/OnBoarding/OnBoarding.tsx
  src/app/profiles/App/OnBoarding/index.tsx
  src/app/profiles/App/OnBoarding/withConnect.ts
Labels: feature ✨

#1088 fix(search): responsive and accent
  src/app/profiles/App/Pages/Profiles/List/ProfileList.tsx
  src/app/profiles/App/Pages/Subscriptions/Subscriptions.tsx
  src/app/profiles/App/Pages/Subscriptions/withConnect.ts
  src/app/profiles/hooks/useContributorsFilters.ts
  src/components/atoms/icons/index.ts
  src/components/molecules/Search/Search.tsx
  src/components/molecules/Search/index.ts
  src/libs/utils/getSearch.ts
  src/libs/utils/getSearchResults.spec.ts
  src/libs/utils/getSearchResults.ts
Labels: bug 🐞

#1094 fix(profile): single profile bannière
  src/app/profiles/App/Pages/Profiles/Profile/ProfileBanner.tsx
  src/app/profiles/App/Pages/Profiles/Profile/ProfileIntro.tsx
  src/components/organisms/Contributor/ContributorLarge.tsx
Labels: bug 🐞

#1096 fix: list contributors ordering
  src/libs/domain/contributor.ts
  src/libs/utils/sortByLocale.ts
Labels: bug 🐞

#1099 fix(onboarding): responsive on height
  src/app/profiles/App/OnBoarding/components/Landing.tsx
  src/app/profiles/App/OnBoarding/components/Line.tsx
  src/app/profiles/App/OnBoarding/components/Modal.tsx
  src/app/theme.ts
Labels: UX :busts_in_silhouette:

#1104 fix(tracking): allow PostHog to be loaded in the Chrom* manifest CSP
  manifest/proding/chromium.js
  manifest/production/chromium.js
  manifest/staging/chromium.js
Labels: bug 🐞
