Repository dis-moi/extension, pull requests merged in 2021-05, with the labels that each got.

#934 feat(seeExampleButton): two step popin
  src/app/profiles/App/Pages/Profiles/ContextPopin.tsx
  src/app/utils/onContributorExampleClick.ts
  src/i18n/resources/en/profiles.json
  src/i18n/resources/fr/profiles.json
Labels: fix-needed 🚫

#947 fix(contextPopin): close after click
  src/app/utils/onContributorExampleClick.ts
Labels: fix-needed 🚫

#867 Update CONTRIBUTING.md - Firefox Staging testing
  docs/CONTRIBUTING.md
  docs/TESTING.md
Labels: documentation

#945 feat(backgroundTranslation): serviceMessage
  src/app/background/index.ts
  src/app/background/sagas/serviceMessage.saga.ts
  src/app/background/sagas/tab.ts
  src/i18n/resources/en/extension.json
  src/i18n/resources/fr/extension.json
Labels: i18n :gb:

#958 Fix/onboarding feedbacks
  src/app/profiles/App/OnBoarding/Steps/Step1.tsx
  src/app/profiles/App/OnBoarding/Steps/Step3.tsx
  src/app/profiles/App/OnBoarding/components/BulleDisMoi.tsx
  src/app/profiles/App/OnBoarding/components/Buttons.tsx
  src/app/profiles/App/OnBoarding/components/Evolution.tsx
  src/app/profiles/App/OnBoarding/components/Landing.tsx
  src/app/profiles/App/OnBoarding/components/Line.tsx
  src/app/profiles/App/OnBoarding/components/Loader.tsx
  src/app/profiles/App/OnBoarding/components/Modal.tsx
  src/app/profiles/App/OnBoarding/components/Top.tsx
  src/assets/video/dismoi-onboarding.mp4
  src/i18n/resources/en/profiles.json
  src/i18n/resources/fr/profiles.json
Labels: bug 🐞, design, help wanted 🖐, high priority

#963 fix(i18n): Fix i18n date formatting
  package.json
  src/i18n/date.ts
  src/i18n/format.spec.ts
  src/i18n/format.ts
  src/i18n/index.ts
  src/i18n/resources/en/extension.json
  src/i18n/resources/fr/extension.json
  yarn.lock
Labels: bug 🐞

#972 fix(i18n): Circular reference on fallbck lng
  src/i18n/date.ts
Labels: bug 🐞, high priority, hot-fix 🚧

#973 Feat/fetch and store matching contexts per contributor #953
  src/api/fetchMatchingContexts.ts
  src/app/actions/index.ts
  src/app/actions/refreshMatchingContexts.ts
  src/app/actions/subscription.ts
  src/app/background/reducers/resources/index.spec.ts
  src/app/background/reducers/resources/index.ts
  src/app/background/reducers/resources/matchingContexts.reducer.spec.ts
  src/app/background/reducers/resources/matchingContexts.reducer.ts
  src/app/background/reducers/subscriptions.reducer.spec.ts
  src/app/background/reducers/subscriptions.reducer.ts
  src/app/background/sagas/connect.saga.ts
  src/app/background/sagas/ratings/notices.saga.ts
  src/app/background/sagas/refreshMatchingContexts.ts
  src/app/background/sagas/subscriptions.saga.ts
  src/app/background/sagas/tab.ts
  src/app/background/selectors/index.spec.ts
  src/app/background/selectors/resources.ts
  src/app/background/selectors/subscriptions.selectors.spec.ts
  src/app/lmem/contributor.ts
  src/app/lmem/matchingContext.ts
  src/app/profiles/store/reducers/matchingContexts.reducer.ts
  src/app/profiles/store/sagas/locationChange.saga.ts
  src/app/profiles/store/sagas/portConnection.saga.ts
  src/app/profiles/store/sagas/windowConnection.saga.ts
  src/app/sagas/sendActionsToBackground.ts
  src/app/store/sagas/fetchNotices.saga.ts
  src/types/index.d.ts
  test/app/actions.ts
  test/fakers/generateContributor.ts
  test/fakers/generateMatchingContext.ts
  test/fakers/generateNotice.ts
Labels: performance 🏁

#976 fix(onBoardingRestart): memoize onboarding
  src/app/profiles/App/OnBoarding/index.tsx
  src/app/utils/isRedirectedFromExtensionInstall.ts
Labels: fix-needed 🚫

#975 test: update Mocha and make it work with Webstorm
  .run/Test.run.xml
  package.json
  tsconfig.json
  yarn.lock
Labels: DX

#959 fix(extension): initialize i18next before store
  src/app/hocs/withTitle.tsx
Labels: :ice_cube: staging, fix-needed 🚫

#983 fix(i18n): date format on translate file
  src/i18n/i18n.spec.ts
  src/i18n/resources/en/profiles.json
  src/i18n/resources/fr/profiles.json
Labels: i18n :gb:

#971 Feat/example link on followed list
  src/app/profiles/App/ContextPopin/ContextPopin.tsx
  src/app/profiles/App/ContextPopin/index.ts
  src/app/profiles/App/ContextPopin/withConnect.ts
  src/app/profiles/App/Pages/Profiles/ContextPopin.tsx
  src/app/profiles/App/Pages/Profiles/List/ProfileList.stories.tsx
  src/app/profiles/App/Pages/Profiles/List/ProfileList.tsx
  src/app/profiles/App/Pages/Profiles/List/withConnect.ts
  src/app/profiles/App/Pages/Subscriptions/Subscriptions.tsx
  src/app/profiles/App/Pages/index.tsx
  src/app/profiles/store/actions/contextPopin.ts
  src/app/profiles/store/reducers/contextPopin.reducer.ts
  src/app/profiles/store/reducers/index.ts
  src/app/profiles/store/selectors/contextPopin.ts
  src/app/utils/onContributorExampleClick.ts
Labels: feature ✨

#995 fix(profileNoticeListItem): fix storybook issue closes #988
  src/app/profiles/App/Pages/Profiles/Profile/ProfileNoticeListItem.tsx
Labels: bug 🐞

#991 chore: remove SendInBlue obsolete references
  .eslintrc.json
  docs/CONTRIBUTING.md
Labels: documentation, technical-debt

#992 chore: quicker git push hook
  package.json
Labels: DX

#1008 chore(profilesonboarding): configure webpack for video assets
  .storybook/webpack.config.js
  src/app/profiles/App/OnBoarding/Steps/Step2.tsx
  src/app/profiles/App/Pages/Profiles/List/ProfileList.tsx
  src/index.d.ts
  webpack.profiles.config.js
Labels: bug 🐞

#1019 refactor(conf): mp4 webpack
  webpack.profiles.config.js
Labels: bug 🐞

#1014 fix(profile): display link
  src/app/profiles/App/Pages/Profiles/Profile/ProfileNoticeListItem.tsx
Labels: bug 🐞

#993 Chore/profiles/explaining video
  src/app/profiles/App/Pages/Profiles/Profile/Profile.tsx
  src/components/atoms/icons/Play.tsx
  src/components/atoms/icons/index.ts
  src/components/molecules/Popin/Popin.stories.tsx
  src/components/molecules/Popin/PopinVideo.tsx
  src/components/molecules/SidebarBox/ExplainingVideoMessageBox.tsx
  src/components/molecules/SidebarBox/SidebarBox.stories.tsx
  src/components/molecules/SidebarBox/index.ts
  src/i18n/resources/en/profiles.json
  src/i18n/resources/fr/profiles.json
Labels: profiles :busts_in_silhouette:

#974 fix(youtubeVideoMessage): use notice state to memoize formated message
  src/components/organisms/NoticeDetails/NoticeDetails.tsx
Labels: bug 🐞

#1021 fix(subscriptions): Fix auto subscriptions
  webpack/config.plugins.js
Labels: bug 🐞

#1022 feat(profiles): Remove old install block when not connected
  src/app/profiles/App/Pages/Profiles/Profile/Profile.tsx
Labels: bug 🐞
