Repository dis-moi/extension, pull requests merged in 2021-11, with the labels that each got.

#1165 Feat/create lmel theme
  .storybook/preview.tsx
  src/app/background/store/sagas/index.ts
  src/app/content/App/index.tsx
  src/app/content/store/sagas/ui/index.tsx
  src/app/profiles/App/index.tsx
  src/components/atoms/Button/Button.tsx
  src/components/atoms/Link/Anchor.ts
  src/components/atoms/Title/Title.ts
  src/components/atoms/icons/Information.tsx
  src/components/atoms/icons/ThumbDown.tsx
  src/components/atoms/icons/ThumbUp.tsx
  src/components/organisms/NoticeDetails/Feedbacks.ts
  src/libs/facets/facet.ts
  src/libs/facets/getTheme.ts
  src/libs/facets/theme.stories.tsx
  src/libs/facets/theme.ts
  src/libs/facets/useTheme.hook.ts
  src/types/styled-components.ts
  webpack.profiles.config.js
  webpack/config.plugins.js
Labels: design, DX, profiles :busts_in_silhouette:, Le Même en Local

#1166 feat: Adapt manifest.json to LMEL facet
  manifest/base.js
  manifest/development/chromium.js
  manifest/development/firefox.js
  manifest/index.js
  manifest/proding/chromium.js
  manifest/proding/firefox.js
  manifest/production/chromium.js
  manifest/production/firefox.js
  manifest/staging/chromium.js
  manifest/staging/firefox.js
  src/components/molecules/Popin/PopinBottomBar.tsx
  src/libs/facets/dismoi.facet.ts
  src/libs/facets/lmel.facet.ts
  src/libs/facets/useFacetName.hook.ts
  webpack/config.plugins.js
Labels: Le Même en Local

#1168 Feat/limit lmel to local contributors
  .env.development.example
  .env.example
  .env.lmel
  .env.proding
  .env.production
  .env.staging
  loadEnv.js
  src/app/background/store/sagas/subscriptions.saga.ts
  src/libs/facets/getFacet.ts
  src/libs/facets/getTheme.ts
  src/libs/facets/useFacetName.hook.ts
  src/libs/store/sagas/refreshContributors.saga.ts
  webpack.profiles.config.js
  webpack/config.plugins.js
Labels: Le Même en Local

#1172 chore: add Chrome Web Store extensions ids for LMEL
  .env.proding.lmel
  .env.production.lmel
  .env.staging.lmel
  loadEnv.js
Labels: chrome, Le Même en Local

#1143 fix(useContributorFilter): reset contributor on change tab
  src/app/profiles/hooks/useContributorsFilters.ts
Labels: bug 🐞

#1175 chore: add Firefox addons ids for LMEL
  .env.proding.lmel
  .env.production.lmel
  .env.staging.lmel
Labels: Le Même en Local

#1179 fix: add website install as postinstall
  package.json
Labels: websiteV2, Le Même en Local

#1185 fix: typo on «Êtes-vous arrivé»
  src/libs/i18n/resources/fr/profiles.json
Labels: bug 🐞, i18n :gb:

#1181 fix: PROFILES_ORIGIN for LMEL
  .env.lmel
Labels: Le Même en Local

#1180 fix: profiles copy to website
  .gitignore
  bin/cpProfilesToWebsite.js
  package.json
  src/app/website/src/components/InjectProfiles.tsx
Labels: websiteV2, Le Même en Local

#1186 fix: PROFILES_ORIGIN must be base url
  .env.lmel
Labels: bug 🐞, Le Même en Local
