Repository dis-moi/extension, pull requests merged in 2021-03, with the labels that each got.

#835 fix(i18n): translator: missingKey fr-FR #833
  src/components/molecules/Popin/PopinBottomBar.tsx
Labels: :ice_cube: staging, bug 🐞, i18n :gb:

#834 feat(profiles): change link: sources to eclaireurs
  src/app/background/sagas/serviceMessage.saga.ts
  src/app/content/App/ServiceMessage/ServiceMessage.stories.tsx
  src/app/profiles/App/Pages/index.tsx
  src/app/profiles/App/ProfileTabs.tsx
  src/app/profiles/App/SimilarProfiles/SimilarProfiles.tsx
  src/app/profiles/App/pathToContributor.ts
  src/app/profiles/routes/index.ts
  src/app/profiles/store/sagas/locationChange.saga.ts
  src/webext/openOptionsTab.ts
Labels: high priority

#841 fix(i18n): button cancel and apos #840
  src/components/organisms/NoticeDetails/NoticeDetails.tsx
  src/i18n/resources/en/extension.json
  src/i18n/resources/fr/extension.json
Labels: bug 🐞

#853 English translation - extension
  src/i18n/resources/en/extension.json
Labels: i18n :gb:

#854 English translation - profiles
  src/i18n/resources/en/profiles.json
Labels: i18n :gb:

#858 feat: redirect path from /en/* to /eclaireurs #852
  src/app/profiles/App/Pages/index.tsx
Labels: high priority

#859 fix(profiles): fltter link all
  src/app/profiles/App/ProfileTabs.tsx
Labels: bug 🐞

#864 fix(Avatar): adds height value
  src/app/profiles/App/Pages/Profiles/Profile/ProfileIntro.tsx
Labels: design, high priority

#866 chore(storybook): change storybook script package.json #865
  package.json
Labels: DX

#873 fix(i18n): t function on withTitle hoc #871
  src/app/content/App/Account/About/index.tsx
  src/app/content/App/Account/Filters/Filters.tsx
  src/app/content/App/Account/Menu/index.tsx
  src/app/content/App/Contribute/ContributeScreen/index.ts
  src/app/content/App/Contribute/PreviewScreen/withTitle.ts
  src/app/content/App/Help/index.tsx
  src/app/content/App/Notice/Details/index.tsx
  src/app/content/App/Question/FormScreen/index.ts
  src/app/content/App/Question/PreviewScreen/withTitle.ts
  src/app/content/App/Subscriptions/index.tsx
  src/app/hocs/withTitle.tsx
  src/components/atoms/Button/AddNoticeButton/AddNoticeButton.tsx
  src/i18n/resources/en/extension.json
  src/i18n/resources/fr/extension.json
Labels: bug 🐞

#848 feat(extension): OnBoarding
  src/app/profiles/App/OnBoarding/OnBoarding.stories.tsx
  src/app/profiles/App/OnBoarding/Steps/Step1.tsx
  src/app/profiles/App/OnBoarding/Steps/Step2.tsx
  src/app/profiles/App/OnBoarding/Steps/Step3.tsx
  src/app/profiles/App/OnBoarding/Steps/index.ts
  src/app/profiles/App/OnBoarding/components/BulleDisMoi.tsx
  src/app/profiles/App/OnBoarding/components/Buttons.tsx
  src/app/profiles/App/OnBoarding/components/Content.tsx
  src/app/profiles/App/OnBoarding/components/Evolution.tsx
  src/app/profiles/App/OnBoarding/components/Landing.tsx
  src/app/profiles/App/OnBoarding/components/Line.tsx
  src/app/profiles/App/OnBoarding/components/Loader.tsx
  src/app/profiles/App/OnBoarding/components/Modal.tsx
  src/app/profiles/App/OnBoarding/components/Text.tsx
  src/app/profiles/App/OnBoarding/components/Title.tsx
  src/app/profiles/App/OnBoarding/components/Top.tsx
  src/app/profiles/App/OnBoarding/components/Video.tsx
  src/app/profiles/App/OnBoarding/index.tsx
  src/app/profiles/App/Pages/Profiles/List/ProfileList.tsx
  src/app/theme.ts
  src/app/utils/isRedirectedFromExtensionInstall.ts
  src/app/utils/useNoScrollBody.ts
  src/assets/video/dismoi-onboarding.mp4
  src/components/atoms/Button/BackgroundButton/BackgroundButton.stories.tsx
  src/components/atoms/Button/BorderButton/BorderButton.ts
  src/components/atoms/Button/Button.tsx
  src/components/atoms/Paragraph/Paragraph.ts
  src/components/atoms/Title/Title.ts
  src/components/atoms/Title1/Title.stories.tsx
  src/components/atoms/Title1/Title1.ts
  src/components/atoms/Title1/index.ts
  src/components/atoms/icons/Bullito.tsx
  src/components/atoms/icons/LogoDisMoiWithD.tsx
  src/components/atoms/icons/Reload.tsx
  src/components/atoms/icons/index.ts
  src/components/molecules/Popin/Popin.tsx
  src/i18n/resources/en/profiles.json
  src/i18n/resources/fr/profiles.json
Labels: feature ✨, high priority

#884 fix(newOnboarding): video link && wording
  src/assets/video/dismoi-onboarding.mp4
  src/i18n/resources/fr/profiles.json
Labels: fix-needed 🚫

#885 fix(newOnboarding): video muted
  src/app/profiles/App/OnBoarding/Steps/Step2.tsx
Labels: fix-needed 🚫
