Repository dis-moi/extension, pull requests merged in 2021-06, with the labels that each got.

#1025 fix(profiles): Fix add to browser install trigger
  src/components/molecules/SidebarBox/ExplainingVideoMessageBox.tsx
Labels: bug 🐞

#1029 doc(profiles): Add deploy profiles app doc
  docs/CONTRIBUTING.md
Labels: documentation

#1031 fix(newBlocksFirefox): change test connected in Profile
  src/app/profiles/App/Pages/Profiles/Profile/Profile.tsx
Labels: bug 🐞

#1034 fix(chunk): onboarding chunk path
  src/app/profiles/App/OnBoarding/OnBoarding.tsx
  src/app/profiles/App/OnBoarding/Steps/index.ts
  src/app/profiles/App/OnBoarding/components/Modal.tsx
  src/app/profiles/App/OnBoarding/index.tsx
  src/app/profiles/App/Pages/Profiles/List/ProfileList.tsx
  views/profiles.pug
  webpack.profiles.config.js
Labels: bug 🐞

#1048 fix(popin): del className bulle-installer
  src/app/profiles/App/ContextPopin/ContextPopin.tsx
Labels: bug 🐞

#1069 feat(i18n): sort by language contributors and notices
  src/app/content/store/selectors/index.ts
  src/app/profiles/store/selectors/contributors.ts
  src/app/profiles/store/selectors/notices.ts
  src/libs/domain/contributor.ts
  src/libs/domain/notice.ts
  src/libs/i18n/index.ts
  src/libs/utils/sortByLocale.ts
  test/fakers/generateContributor.ts
  test/fakers/generateNotice.ts
Labels: feature ✨, i18n :gb:
