Repository dis-moi/extension, pull requests merged in 2021-04, with the labels that each got.

#875 fix(NoticesList): way to display more than 2 notices
  src/app/content/App/Notice/List/List.stories.tsx
  src/app/content/App/Notice/List/ListContainer.ts
  src/app/content/App/Notice/List/index.tsx
  src/components/atoms/AddNoticeContainer.ts
  src/components/atoms/Button/AddNoticeButton/AddNoticeButton.tsx
  src/components/organisms/Notice/Container.ts
  src/components/organisms/Notice/Content.ts
Labels: Ideas :bulb:, UX :busts_in_silhouette:, WIP 👷, design, help wanted 🖐

#889 fix(Notices): youtube regex with link
  src/app/utils/getMessageWithMediaPlayer.spec.ts
  src/app/utils/getMessageWithMediaPlayer.ts
  src/components/organisms/NoticePreview.stories.tsx
  test/fakers/generateNotice.ts
Labels: feature ✨

#886 Feat/router en
  package.json
  src/app/background/sagas/serviceMessage.saga.ts
  src/app/content/App/Account/About/index.tsx
  src/app/content/App/Help/index.tsx
  src/app/content/App/ServiceMessage/ServiceMessage.stories.tsx
  src/app/content/App/Subscriptions/withConnect.ts
  src/app/hooks/useChangeLanguage.ts
  src/app/profiles/App/Pages/index.tsx
  src/app/profiles/App/ProfileTabs.tsx
  src/app/profiles/App/SimilarProfiles/SimilarProfiles.tsx
  src/app/profiles/App/pathToContributor.ts
  src/app/profiles/routes/index.ts
  src/app/profiles/store/sagas/locationChange.saga.ts
  src/app/store/sagas/effects/takeLatestLocationChange.ts
  src/i18n/index.ts
  src/i18n/resources/en/extension.json
  src/i18n/resources/en/profiles.json
  src/i18n/resources/fr/extension.json
  src/i18n/resources/fr/profiles.json
  src/webext/openOptionsTab.ts
  yarn.lock
Labels: WIP 👷, i18n :gb:

#895 fix(routerEn): ProfileTabs links
  src/app/profiles/App/ProfileTabs.tsx
  yarn.lock
Labels: bug 🐞

#908 docs(i18n): add new readme
  docs/CONTRIBUTING.md
  docs/I18N.md
Labels: documentation, i18n :gb:

#915 fix: extension completely hangs after 6|10 retries
  src/app/background/sagas/refreshMatchingContexts.ts
  src/app/sagas/effects/callAndRetry.ts
  src/app/store/sagas/refreshContributors.saga.ts
Labels: bug 🐞, chrome, firefox, hot-fix 🚧

#918 perf: debounce matching-contexts refresh triggers
  src/app/background/sagas/refreshMatchingContexts.ts
Labels: performance 🏁

#919 perf: change contributors periodical refresh logic
  src/app/background/sagas/refreshContributors.ts
Labels: performance 🏁

#917 perf: change matching contexts periodical refresh logic
  src/app/background/sagas/refreshMatchingContexts.ts
Labels: performance 🏁

#932 fix(messageWithYoutubePlayer): display video after text
  src/app/utils/getMessageWithMediaPlayer.spec.ts
  src/app/utils/getMessageWithMediaPlayer.ts
Labels: fix-needed 🚫

#903 feat(onBoardingEvolution): detect isChrome for step2, change wording
  src/app/profiles/App/OnBoarding/Steps/Step1.tsx
  src/app/profiles/App/OnBoarding/Steps/Step2.tsx
  src/app/profiles/App/OnBoarding/Steps/Step3.tsx
  src/app/profiles/App/OnBoarding/components/Buttons.tsx
  src/app/profiles/App/OnBoarding/components/Line.tsx
  src/app/profiles/App/OnBoarding/components/Title.tsx
  src/app/profiles/App/OnBoarding/components/Top.tsx
  src/app/profiles/App/OnBoarding/index.tsx
  src/app/utils/isChrome.ts
  src/i18n/resources/en/profiles.json
  src/i18n/resources/fr/profiles.json
Labels: Onboarding, feature ✨
